name: Collect diagnostics
description: Gather logs and pack diagnostics zip into dist/
inputs:
  job_name:
    description: Short job name (e.g., fast-tests, pipeline-smoke)
    required: false
    default: job
runs:
  using: composite
  steps:
    - name: Run collector
      shell: bash
      run: |
        set -euo pipefail
        DIR="${GITHUB_ACTION_PATH}"
        bash "$DIR/collect.sh" "${{ inputs.job_name }}"
