required:
  - event_id
  - country_name
  - iso3
  - hazard_code
  - hazard_label
  - hazard_class
  - metric
  - value
  - unit
  - as_of_date
  - publication_date
  - publisher
  - source_type
  - source_url
  - doc_title
  - definition_text
  - method
  - confidence
  - revision
  - ingested_at

enums:
  metric: [in_need, affected, displaced, cases]
  unit: [persons, persons_cases]

optional:
  series_semantics:
    type: string
    enum: [stock, new]
    required: false
  value_new:
    type: number
    required: false
  value_stock:
    type: number
    required: false
  rebase_flag:
    type: integer
    required: false
  first_observation:
    type: integer
    required: false
  delta_negative_clamped:
    type: integer
    required: false
