name: Canary Gate

on:
  pull_request:
    branches:
      - codex/**
  push:
    branches:
      - codex/**

concurrency:
  group: canary-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  canary:
    runs-on: ubuntu-latest
    env:
      CANARY_REPORT: ${{ github.workspace }}/.ci/canary_results.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints-ci.txt -e '.[db,connectors]'

      - name: Run canary tests
        id: canary
        continue-on-error: true
        run: |
          python -m scripts.ci.run_canary --report "$CANARY_REPORT"

      - name: Comment on failure
        if: ${{ steps.canary.outcome == 'failure' && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = process.env.CANARY_REPORT;
            let failedTests = [];
            try {
              const payload = JSON.parse(fs.readFileSync(path, 'utf8'));
              failedTests = payload.failed_tests || [];
            } catch (error) {
              core.warning(`Unable to parse canary report at ${path}: ${error}`);
            }
            const list = failedTests.length ? failedTests.map(test => `- ${test}`).join('\n') : '- Unable to determine failing tests. Check the logs.';
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const body = [
              '🚨 **Canary Gate failed**.',
              '',
              'Failed tests:',
              list,
              '',
              `Logs: ${runUrl}`,
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });

      - name: Label PR
        if: ${{ steps.canary.outcome == 'failure' && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-fix/canary

      - name: Fail job if canary failed
        if: ${{ steps.canary.outcome == 'failure' }}
        run: exit 1
