---
name: "Resolver pipeline — smoke"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: resolver-pipeline-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: "Smoke pipeline (stubs)"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYTHONUNBUFFERED: "1"
      PERIOD_LABEL: ci-smoke
      RESOLVER_PERIOD: ci-smoke
      RESOLVER_STAGING_DIR: data/staging
      RESOLVER_INGESTION_MODE: stubs
      RESOLVER_FAIL_ON_STUB_ERROR: "0"
      RESOLVER_DEBUG: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install resolver dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r resolver/requirements.txt
          pip install 'duckdb>=1.0,<2.0'

      - name: Reset staging directories
        run: |
          set -euo pipefail
          rm -rf "data/staging/${PERIOD_LABEL}"
          rm -rf "data/snapshots/${PERIOD_LABEL}"

      - name: Prepare raw staging (stubs)
        env:
          PERIOD_LABEL: ci-smoke
        shell: bash
        run: |
          set -euo pipefail
          RAW="data/staging/${PERIOD_LABEL}/raw"
          mkdir -p "$RAW"
          python -m resolver.ingestion.ifrc_go_stub --out "$RAW"
          echo "Raw contents:"
          ls -lh "$RAW" || true

      - name: Discover normalizable sources
        env:
          PERIOD_LABEL: ci-smoke
        shell: bash
        run: |
          set -euo pipefail
          python scripts/ci/discover_normalizable_sources.py "${PERIOD_LABEL}" | tee _sources.env
          grep "^SOURCES=" _sources.env >> "$GITHUB_ENV"

      - name: Normalize
        env:
          PERIOD_LABEL: ci-smoke
          SOURCES: ${{ env.SOURCES }}
        run: |
          set -euo pipefail
          python -m resolver.transform.normalize \
            --in "data/staging/${PERIOD_LABEL}/raw" \
            --out "data/staging/${PERIOD_LABEL}/canonical" \
            --period "${PERIOD_LABEL}" \
            --sources "${SOURCES}"
      - name: Load / derive / export
        env:
          PERIOD_LABEL: ci-smoke
        run: |
          set -euo pipefail
          python -m resolver.tools.load_and_derive load-canonical \
            --in "data/staging/${PERIOD_LABEL}/canonical"
          python -m resolver.tools.load_and_derive derive-deltas \
            --period "${PERIOD_LABEL}" --allow-negatives 1
          python -m resolver.tools.load_and_derive export \
            --period "${PERIOD_LABEL}" --format parquet \
            --out "data/snapshots/${PERIOD_LABEL}"

      - name: Collect diagnostics (smoke)
        if: always()
        uses: ./.github/actions/collect-diagnostics
        with:
          job_name: pipeline-smoke

      - name: Upload diagnostics summary (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary-pipeline-smoke-${{ github.run_id }}-${{ github.run_attempt }}
          path: ${{ env.SUMMARY_PATH }}
          if-no-files-found: ignore
          retention-days: 7
          overwrite: true

      - name: Upload diagnostics (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-pipeline-smoke-${{ github.run_id }}-${{ github.run_attempt }}
          path: dist/diagnostics-pipeline-smoke-${{ github.run_id }}-${{ github.run_attempt }}.zip
          if-no-files-found: ignore
          retention-days: 7
          overwrite: true

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resolver-smoke-snapshots
          path: data/snapshots/${PERIOD_LABEL}/*.parquet
          if-no-files-found: error
          retention-days: 7
          overwrite: true
