name: Forecast on Metaculus Cup (every 2 days @ 00:00 UTC)

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  forecast_job:
    runs-on: ubuntu-latest

    env:
      # Routing
      RUN_PLAYLIST: "cup"
      METACULUS_COLLECTION_SLUG_CUP: "metaculus-cup"
      TOURNAMENT_ID: "metaculus-cup"
      SUBMIT_PREDICTION: "1"

      # Required
      METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}

      # GPT-* via OpenRouter (only this leg via OR)
      USE_OPENROUTER: "1"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
      OPENROUTER_GPT5_ID: "openai/gpt-4o"
      OPENROUTER_GPT5_THINK_ID: "openai/gpt-4o"
      OPENROUTER_FALLBACK_ID: "openai/gpt-4o"

      # Anthropic Claude via OpenRouter
      USE_ANTHROPIC: "1"
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ANTHROPIC_BASE_URL: "https://openrouter.ai/api/v1"
      OPENROUTER_CLAUDE37_ID: "anthropic/claude-3.7-sonnet"

      # Google Gemini (direct)
      USE_GOOGLE: "1"
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GEMINI_MODEL: "gemini-2.5-pro"

      # xAI Grok (direct)
      ENABLE_GROK: "1"
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      XAI_GROK_ID: "grok-4"

      # AskNews (for research)
      enable_asknews: "1"
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}

      # Market snapshot tuning
      ENABLE_MARKET_SNAPSHOT: "1"
      MARKET_SNAPSHOT_MAX_MATCHES: "3"
      METACULUS_INCLUDE_RESOLVED: "1"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Purge research + actor caches (Cup runs only)
        run: |
          rm -f cache/research_llm__*.json || true
          rm -f cache/actors__*.json || true

      - name: "Preflight: verify collection slug returns open questions"
        shell: bash
        run: |
          set -euo pipefail
          COLL="${METACULUS_COLLECTION_SLUG_CUP}"
          code=$(curl -s -o /tmp/coll.json -w "%{http_code}" \
            -H "Authorization: Token ${METACULUS_TOKEN}" \
            "https://www.metaculus.com/api2/questions/?collection=${COLL}&status=open&limit=1")
          echo "HTTP: $code"
          if [ "$code" != "200" ]; then
            echo "❌ Bad response:"; cat /tmp/coll.json; exit 1
          fi
          jq .results[0].id /tmp/coll.json || true

      - name: Run Spagbot on Metaculus Cup (fresh)
        run: |
          poetry run python spagbot.py --mode run --fresh-research

      - name: Git commit any changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add forecasts.csv forecasts_by_model.csv forecasts_mcq_wide.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update forecast data from spagbot run [skip ci]"
            git push
          else
            echo "No new forecast data to commit."
          fi

      - name: Upload Spagbot outputs (logs, CSVs, calibration)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spagbot-run-${{ github.run_id }}
          if-no-files-found: warn
          retention-days: 180
          path: |
            forecast_logs/**
            logs/**
            forecasts.csv
            forecasts_by_model.csv
            data/calibration_advice.txt
