name: Test Bot (use cache)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  forecast_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Spagbot test set (cached)
        run: |
          poetry run python spagbot.py --mode test_questions --limit 3
        env:
          # Required
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}

          # GPT-* via OpenRouter (only this leg via OR)
          USE_OPENROUTER: "1"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: "https://openrouter.ai/api/v1"
          OPENROUTER_GPT5_ID: "openai/gpt-4o"
          OPENROUTER_GPT5_THINK_ID: "openai/gpt-4o"
          OPENROUTER_FALLBACK_ID: "openai/gpt-4o"

          # Anthropic Claude via OpenRouter
          USE_ANTHROPIC: "1"
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_BASE_URL: "https://openrouter.ai/api/v1"
          OPENROUTER_CLAUDE37_ID: "anthropic/claude-3.7-sonnet"

          # Google Gemini (direct)
          USE_GOOGLE: "1"
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL: "gemini-2.5-pro"

          # xAI Grok (direct)
          ENABLE_GROK: "1"
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          XAI_GROK_ID: "grok-4"

          # AskNews (for research)
          enable_asknews: "1"
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}

          # Market snapshot tuning
          ENABLE_MARKET_SNAPSHOT: "1"
          MARKET_SNAPSHOT_MAX_MATCHES: "3"
          METACULUS_INCLUDE_RESOLVED: "1"
